### ISSUE TITLE
Images not displayed in SMILES-LSTM-Walkthrough.ipynb

### ISSUE THREAD

**Issue by chrulm** [rociomer/dl-chem-101#5]
Hi, the illustrative images for the `SMILES-LSTM-Walkthrough.ipynb` are not rendered correctly in the GitHub preview. It also does not show for me in GitHub Codespace or when I clone it locally. 

@GuoJeff could you take a look at this?

Thanks for this helpful walkthrough!

It looks like this:
![image](https://user-images.githubusercontent.com/39857842/202796656-4f575d6a-0d17-45b9-8541-68b2fe502334.png)

**Comment by GuoJeff** [comment]
Hi @chrulm,

Sorry for the delayed response and thank you for checking out the walkthrough! Please let me know if there are other bugs.
