### ISSUE TITLE
ModuleNotFoundError: No module named 'pred_ffn'

### ISSUE THREAD

**Issue by SaraiQX** [rociomer/dl-chem-101#7]
Hi Dr Mercado,
Thanks for this wonderful tutorial.
I'm experimenting with the task "01_prop_pred_FFN". When I tried to run "run_scripts/train_ffn.py" in my local env (with exact requirement.txt being satisfied),  the error as titled occurred.

Should there be more necessary libs? Thank you!
Sarai

**Comment by samgoldman97** [comment]
Hi Sarai, 
The pred_ffn module is the name of the package. Have you executed `python setup.py develop` with the environment active, as suggested in the README install section [here](https://github.com/rociomer/dl-chem-101/tree/main/01_prop_pred_FFN#install)? I would expect this to fix the problem.

Best,
Sam

**Comment by SaraiQX** [comment]
Hi Sam,
Thank you for the reminder. I did miss the `python setup.py develop` at first.  Please don't mind my lengthy feedback. 
Following that command and then next, however, the same error still exit.
With refreshed python package/module principle😂 I found that the `src ` folder contains the `pred_ffn` folder which may cause the error. So I moved the  `pred_ffn` folder to the upper level, and add two lines as below:

```
import sys
sys.path.append('/Users/.../01_prop_pred_FFN')
```
The ModuleNotFoundError disappeared, and a new issue came up :
```
Traceback (most recent call last):
  File "/Users/xxx/01_prop_pred_FFN/run_scripts/train_ffn.py", line 11, in <module>
    train.train_model()
  File "/Users/xxx/01_prop_pred_FFN/pred_ffn/train.py", line 42, in train_model
    utils.setup_logger(save_dir,
  File "/Users/xxx/01_prop_pred_FFN/pred_ffn/utils.py", line 17, in setup_logger
    save_dir.mkdir(exist_ok=True)
  File "/Users/xxx/opt/anaconda3/envs/dl-chem/lib/python3.8/pathlib.py", line 1288, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'results/example_run'
```
Then I change `save_dir.mkdir(exist_ok=True)` into  `save_dir.mkdir(parents=True,exist_ok=True)` and the train_ffn.py run smoonthly😄 That's all for my experience now.
Thank you again for opening a window for beginners like me.

Merry Christmas in advance~
Sarai
